services:
  radarr:
    build:
      context: .
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./movies:/movies
    ports:
      - 7878:7878
